In [ ]:
import torch
def perturbation_loss(perturbation, watermark, c=0.1, watermark_region=4):
    weighted_perturbation = torch.matmul(perturbation, (1 + watermark * watermark_region))
    l2_norm = torch.norm(weighted_perturbation, p=2)
        
    threshold_loss = torch.max(torch.zeros_like(l2_norm), l2_norm - c)
    
    
    return threshold_loss # + small_perturbation_penalty

In [4]:
perturbation = torch.rand(2, 3,512,512)
watermark = torch.rand(2, 3, 512,512)

In [14]:
perturbation

tensor([[[[0.6725, 0.7413, 0.7929,  ..., 0.5837, 0.2065, 0.0213],
          [0.9730, 0.2210, 0.5418,  ..., 0.5965, 0.4083, 0.9889],
          [0.8888, 0.7750, 0.1477,  ..., 0.9174, 0.5300, 0.7242],
          ...,
          [0.0033, 0.4357, 0.7100,  ..., 0.5257, 0.9974, 0.9401],
          [0.3723, 0.8426, 0.5489,  ..., 0.4890, 0.4110, 0.0456],
          [0.4656, 0.5668, 0.7936,  ..., 0.2147, 0.0833, 0.6995]],

         [[0.6624, 0.0257, 0.4838,  ..., 0.4887, 0.7424, 0.1304],
          [0.2269, 0.3477, 0.7542,  ..., 0.2101, 0.3607, 0.5744],
          [0.9883, 0.6144, 0.3243,  ..., 0.3981, 0.4077, 0.6222],
          ...,
          [0.8823, 0.2361, 0.0551,  ..., 0.1058, 0.8929, 0.7038],
          [0.3227, 0.8715, 0.9242,  ..., 0.7660, 0.6021, 0.4372],
          [0.9961, 0.2483, 0.3590,  ..., 0.9994, 0.4361, 0.8176]],

         [[0.2146, 0.2258, 0.7901,  ..., 0.3376, 0.7228, 0.1849],
          [0.0993, 0.4566, 0.3575,  ..., 0.6481, 0.6360, 0.2141],
          [0.3613, 0.7325, 0.0369,  ..., 0

In [19]:
weighted_perturbation = torch.matmul(perturbation, (1 + watermark * 4))
weighted_perturbation

tensor([[[[754.4260, 774.0959, 762.6484,  ..., 724.0464, 736.3914, 763.8325],
          [834.9896, 850.9899, 857.3152,  ..., 808.4569, 817.6003, 864.0143],
          [774.2481, 798.2277, 814.1394,  ..., 751.4556, 773.7832, 797.3362],
          ...,
          [734.6733, 736.2500, 763.1962,  ..., 705.0249, 727.4561, 764.5430],
          [786.6219, 788.4650, 803.2338,  ..., 760.3738, 751.2289, 808.7074],
          [821.3408, 812.6008, 826.6532,  ..., 771.2612, 796.5640, 829.3737]],

         [[760.0929, 775.1162, 772.5265,  ..., 769.8328, 776.0662, 783.7380],
          [753.5253, 778.0947, 765.3613,  ..., 767.3505, 760.4154, 761.8924],
          [762.8608, 781.7604, 774.7224,  ..., 772.9425, 788.0441, 800.1527],
          ...,
          [720.4720, 767.4631, 742.0798,  ..., 738.3911, 749.7259, 769.3419],
          [767.6211, 779.9188, 778.6799,  ..., 806.1976, 773.5894, 794.7400],
          [769.9332, 803.7879, 797.9863,  ..., 800.8680, 795.2625, 797.2012]],

         [[773.3931, 762.4849,

In [17]:
weighted_perturbation = perturbation * (1 + watermark * 4)
weighted_perturbation

tensor([[[[1.6986e+00, 1.2015e+00, 2.8150e+00,  ..., 1.6951e+00,
           6.1665e-01, 1.0234e-01],
          [2.2593e+00, 2.4858e-01, 1.4679e+00,  ..., 2.3913e+00,
           1.2598e+00, 3.3831e+00],
          [4.2261e+00, 2.5575e+00, 3.1323e-01,  ..., 2.2883e+00,
           2.2525e+00, 2.8115e+00],
          ...,
          [4.5008e-03, 9.3876e-01, 2.2947e+00,  ..., 2.3308e+00,
           1.3845e+00, 3.3023e+00],
          [6.8051e-01, 3.8578e+00, 1.3912e+00,  ..., 9.7303e-01,
           8.2741e-01, 1.5828e-01],
          [5.2988e-01, 1.2230e+00, 2.7152e+00,  ..., 5.1611e-01,
           1.0344e-01, 3.4096e+00]],

         [[2.5960e+00, 4.3389e-02, 1.8605e+00,  ..., 1.7981e+00,
           1.7923e+00, 4.8927e-01],
          [7.0940e-01, 1.0032e+00, 7.9037e-01,  ..., 6.4500e-01,
           5.4125e-01, 7.0413e-01],
          [2.8895e+00, 2.4811e+00, 1.2319e+00,  ..., 1.1118e+00,
           1.1206e+00, 3.0604e+00],
          ...,
          [4.4055e+00, 9.7472e-01, 1.4977e-01,  ..., 5.1817

In [7]:
weighted_perturbation.shape

torch.Size([2, 3, 512, 512])

In [25]:
def l2norm(X, dim, eps=1e-8):
    """L2-normalize columns of X
    """
    norm = torch.pow(X, 2).sum(dim=dim, keepdim=True).sqrt() + eps
    X = torch.div(X, norm)
    return X

l2_norm = l2norm(weighted_perturbation, dim=1)
l2_norm

tensor([[[[0.5711, 0.5800, 0.5736,  ..., 0.5575, 0.5581, 0.5670],
          [0.6038, 0.5977, 0.6129,  ..., 0.5915, 0.5951, 0.6091],
          [0.5776, 0.5825, 0.5949,  ..., 0.5640, 0.5697, 0.5734],
          ...,
          [0.5699, 0.5550, 0.5777,  ..., 0.5491, 0.5554, 0.5613],
          [0.5909, 0.5865, 0.5964,  ..., 0.5709, 0.5726, 0.5907],
          [0.5942, 0.5804, 0.5915,  ..., 0.5625, 0.5794, 0.5874]],

         [[0.5754, 0.5807, 0.5810,  ..., 0.5928, 0.5882, 0.5818],
          [0.5449, 0.5465, 0.5472,  ..., 0.5614, 0.5534, 0.5371],
          [0.5691, 0.5705, 0.5661,  ..., 0.5801, 0.5802, 0.5754],
          ...,
          [0.5589, 0.5786, 0.5617,  ..., 0.5751, 0.5724, 0.5648],
          [0.5766, 0.5801, 0.5781,  ..., 0.6053, 0.5896, 0.5805],
          [0.5570, 0.5741, 0.5710,  ..., 0.5841, 0.5784, 0.5646]],

         [[0.5855, 0.5713, 0.5775,  ..., 0.5812, 0.5853, 0.5832],
          [0.5819, 0.5867, 0.5701,  ..., 0.5787, 0.5828, 0.5836],
          [0.5852, 0.5789, 0.5706,  ..., 0

In [26]:
l2_norm.shape

torch.Size([2, 3, 512, 512])